allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  '@serialport/bindings-cpp': true
  node-bluetooth: true
  '@plantae-tech/inkpresser': true
  '@ssxv/node-printer': true
